package com.example.meetbook

/*Deklarasi Key untuk menyimpan data dalam onSaveInstanceState*/
const val EXTRA_UNAME =  "EXTRA_UNAME"

const val EXTRA_CLIENT_DATA = "CLIENTDATA123"
const val ARG_CLIENT_NAME = "ARGCLIENT12345"
const val ARG_GET_ROOM_TITLE = "ARGROOMTITLE123"
const val ARG_GET_ROOM_CAP = "ARGROOMCAP123"
const val ARG_GET_ROOM_IMAGE = "ARGROOMIMAGE123"
const val JOB_ID_MEETING_PROGRESS = 13467982
const val ACTION_MEETING = "ACTIONMEET123"
const val EXTRA_MEETING_PERCENTAGE = "EMP123"
const val EXTRA_MEETING_FINISH = "EMF123"
const val EXTRA_MEETING_DURATION = "MEETDUR123"
const val EXTRA_NOTIFICATION_MEETING = 77337
const val ID_CHANNEL_START = "MEETINGSTART123"
const val ID_CHANNEL_FINISH = "MEETINGFINISH123"
const val ID_GROUP_START = "MEETINGSTARTGROUP123"
const val ID_GROUP_FINISH = "MEETINGFINISHGROUP123"

const val EXTRA_USERNAME_INSTANCE = "user_name_instance"
const val EXTRA_PASSWORD_INSTANCE = "pass_word_instance"